name       : xfce4-notifyd
version    : 0.8.2
release    : 3
source     :
    - https://archive.xfce.org/src/apps/xfce4-notifyd/0.8/xfce4-notifyd-0.8.2.tar.bz2 : e3a28adb08daa1411135142a0d421e4d6050c4035a4e513a673a59460ff2ae84
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Notification daemon for the Xfce desktop.
description: |
    Notification daemon for the Xfce desktop.
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(libnotify)
    - pkgconfig(libxfce4panel-2.0)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libxfconf-0)
    - pkgconfig(sqlite3)
setup      : |
    %configure \
        --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install
